### ISSUE TITLE
Dependabot issue on git.apache.org/thrift.git@v0.12.0:

### ISSUE THREAD

**Issue by ns-sjli** [mvmaasakkers/certificates#25]
Hi @mvmaasakkers ,

the `go.mod` file is using `git.apache.org/thrift.git@v0.12.0` which causes github Dependabot error as the following:

```
Dependabot` can't resolve your Go dependency files
Dependabot failed to update your dependencies because there was an error resolving your Go dependency files.

Dependabot encountered the following error:

go: github.com/mvmaasakkers/certificates@v0.6.0 requires
	git.apache.org/thrift.git@v0.12.0: reading git.apache.org/thrift.git/go.mod at revision v0.12.0: unknown revision
[Learn more](https://docs.github.com/github/managing-security-vulnerabilities/troubleshooting-dependabot-errors)
```

Similar issues: https://github.com/hashicorp/vault/issues/7475

Would it be possible, we update the `go.mod` as well as go version to 1.18. Thank you

**Comment by jeffwidman** [comment]
See also https://github.com/dependabot/dependabot-core/issues/4530#issuecomment-1002834579, even though the underlying server should be up, it has rate-limiting that results in breaking dependabot.
