### ISSUE TITLE
Add more tests for rand.go

### ISSUE THREAD

**Issue by enthiric** [mvmaasakkers/certificates#3]
Please add a test that runs the fn multiple times and validates that each value is different than the last one.

https://github.com/mvmaasakkers/certificates/blob/020fb015e7dd252861f94d17dcbf6b0acfa0cae3/cert/rand_test.go#L7

**Comment by mvmaasakkers** [comment]
Done: https://github.com/mvmaasakkers/certificates/blob/master/cert/rand_test.go#L30
